name: 'Setup pandoc'
description: 'Setup pandoc and add it to your PATH'
author: 'Niklas Mollenhauer'
inputs:
  pandoc-version:
    required: false
    default: 'latest'
    description: |
      Exact version of pandoc to use.
      You can find available versions here:
      https://github.com/jgm/pandoc/releases
runs:
  using: 'node16'
  main: 'lib/setup-pandoc.js'
